services:
  - type: web
    name: nexhost-v4
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PORT
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
