"""
NexHost V4 - Project Manager
=============================
Project CRUD operations with Hot Reload support
"""

import os
import shutil

class ProjectManager:
    def __init__(self, database, uploads_dir):
        self.db = database
        self.uploads_dir = uploads_dir
    
    def create_project(self, user_id, name, description, language, main_file):
        """Create new project"""
        # Create project in database
        result = self.db.create_project(user_id, name, description, language, main_file)
        
        if result['success']:
            project_id = result['project_id']
            # Create project directory
            project_path = os.path.join(self.uploads_dir, str(user_id), str(project_id))
            os.makedirs(project_path, exist_ok=True)
            
            # Create default files based on language
            if language == 'python':
                self._create_python_template(project_path, main_file)
        
        return result
    
    def _create_python_template(self, project_path, main_file):
        """Create Python project template"""
        main_path = os.path.join(project_path, main_file)
        with open(main_path, 'w', encoding='utf-8') as f:
            f.write('''#!/usr/bin/env python3
"""
NexHost Project - Python Script
================================
Generated by NexHost Panel V4
"""

import os
import sys
import time
import logging

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def main():
    """Main function"""
    logger.info("🚀 Script started successfully!")
    
    try:
        # Your code here
        while True:
            logger.info("✅ Script is running...")
            time.sleep(10)
            
    except KeyboardInterrupt:
        logger.info("👋 Script stopped by user")
    except Exception as e:
        logger.error(f"❌ Error: {e}")
        raise

if __name__ == '__main__':
    main()
''')
        
        # Create requirements.txt
        req_path = os.path.join(project_path, 'requirements.txt')
        with open(req_path, 'w', encoding='utf-8') as f:
            f.write('# Add your dependencies here\n')
        
        # Create .env template
        env_path = os.path.join(project_path, '.env')
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write('# Environment Variables\n')
            f.write('DEBUG=false\n')
    
    def get_project(self, project_id, user_id, user_role):
        """Get project by ID with permission check"""
        project = self.db.get_project(project_id)
        
        if not project:
            return {'success': False, 'error': 'Project not found'}
        
        # Check permissions
        if user_role not in ['admin', 'superadmin'] and project['user_id'] != user_id:
            return {'success': False, 'error': 'Access denied'}
        
        return {'success': True, 'project': project}
    
    def get_projects(self, user_id, user_role):
        """Get all projects for user"""
        if user_role in ['admin', 'superadmin']:
            return self.db.get_all_projects()
        else:
            return self.db.get_projects_by_user(user_id)
    
    def update_project(self, project_id, user_id, user_role, data):
        """Update project"""
        # Check permissions
        project = self.db.get_project(project_id)
        if not project:
            return {'success': False, 'error': 'Project not found'}
        
        if user_role not in ['admin', 'superadmin'] and project['user_id'] != user_id:
            return {'success': False, 'error': 'Access denied'}
        
        return self.db.update_project(project_id, data)
    
    def delete_project(self, project_id, user_id, user_role):
        """Delete project"""
        # Check permissions
        project = self.db.get_project(project_id)
        if not project:
            return {'success': False, 'error': 'Project not found'}
        
        if user_role not in ['admin', 'superadmin'] and project['user_id'] != user_id:
            return {'success': False, 'error': 'Access denied'}
        
        # Delete project directory
        project_path = os.path.join(self.uploads_dir, str(project['user_id']), str(project_id))
        if os.path.exists(project_path):
            shutil.rmtree(project_path)
        
        # Delete from database
        return self.db.delete_project(project_id)
    
    def update_status(self, project_id, status, pid=None):
        """Update project status"""
        self.db.update_project_status(project_id, status, pid)
    
    def get_project_stats(self, project_id):
        """Get project statistics"""
        project = self.db.get_project(project_id)
        if not project:
            return None
        
        project_path = os.path.join(self.uploads_dir, str(project['user_id']), str(project_id))
        
        # Calculate directory size
        total_size = 0
        file_count = 0
        
        if os.path.exists(project_path):
            for dirpath, dirnames, filenames in os.walk(project_path):
                for f in filenames:
                    fp = os.path.join(dirpath, f)
                    if os.path.exists(fp):
                        total_size += os.path.getsize(fp)
                        file_count += 1
        
        return {
            'size': total_size,
            'file_count': file_count,
            'path': project_path
        }
    
    def hot_reload(self, project_id, user_id, user_role, file_path, new_file_content, process_runner=None):
        """Hot reload - update file and restart project"""
        # Check permissions
        project = self.db.get_project(project_id)
        if not project:
            return {'success': False, 'error': 'Project not found'}
        
        if user_role not in ['admin', 'superadmin'] and project['user_id'] != user_id:
            return {'success': False, 'error': 'Access denied'}
        
        project_path = os.path.join(self.uploads_dir, str(project['user_id']), str(project_id))
        full_file_path = os.path.join(project_path, file_path)
        
        # Security check - ensure file is within project directory
        real_project_path = os.path.realpath(project_path)
        real_file_path = os.path.realpath(full_file_path)
        if not real_file_path.startswith(real_project_path):
            return {'success': False, 'error': 'Invalid file path'}
        
        # Check if file exists
        if not os.path.exists(full_file_path):
            return {'success': False, 'error': 'File not found'}
        
        # Check if it's a Python file
        if not file_path.endswith('.py'):
            return {'success': False, 'error': 'Only Python files can be hot reloaded'}
        
        try:
            # Check if project is running
            was_running = False
            if process_runner and process_runner.is_running(project_id):
                was_running = True
                # Stop the project
                process_runner.stop_project(project_id)
                self.update_status(project_id, 'stopped')
            
            # Create backup of old file
            backup_path = full_file_path + '.backup.py'
            shutil.copy2(full_file_path, backup_path)
            
            # Write new content
            with open(full_file_path, 'w', encoding='utf-8') as f:
                f.write(new_file_content)
            
            # Restart if it was running
            if was_running and process_runner:
                result = process_runner.start_project(
                    project_id=project_id,
                    project_path=project_path,
                    main_file=project['main_file'],
                    language=project['language']
                )
                
                if result['success']:
                    self.update_status(project_id, 'running', result.get('pid'))
                    return {
                        'success': True,
                        'message': 'File updated and project restarted successfully',
                        'new_status': 'running',
                        'backup_created': True
                    }
                else:
                    return {
                        'success': True,
                        'message': 'File updated but project failed to restart: ' + result.get('error', 'Unknown error'),
                        'new_status': 'stopped',
                        'backup_created': True
                    }
            
            return {
                'success': True,
                'message': 'File updated successfully',
                'new_status': 'stopped',
                'backup_created': True
            }
            
        except Exception as e:
            return {'success': False, 'error': str(e)}
    
    def restore_backup_file(self, project_id, user_id, user_role, file_path):
        """Restore file from backup"""
        # Check permissions
        project = self.db.get_project(project_id)
        if not project:
            return {'success': False, 'error': 'Project not found'}
        
        if user_role not in ['admin', 'superadmin'] and project['user_id'] != user_id:
            return {'success': False, 'error': 'Access denied'}
        
        project_path = os.path.join(self.uploads_dir, str(project['user_id']), str(project_id))
        full_file_path = os.path.join(project_path, file_path)
        backup_path = full_file_path + '.backup.py'
        
        # Check if backup exists
        if not os.path.exists(backup_path):
            return {'success': False, 'error': 'Backup file not found'}
        
        try:
            # Restore from backup
            shutil.copy2(backup_path, full_file_path)
            return {
                'success': True,
                'message': 'File restored from backup'
            }
        except Exception as e:
            return {'success': False, 'error': str(e)}
